version: '3'
services:  
  parity:
    image: parity/parity
    ports:
      - "8545:8545"
      - "8546:8546"
      - "3030:3030"
    volumes:
      - ./parity:/parity
    command: >
      --base-path /parity
      --geth
      --config /parity/config.toml

