# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Parity syncs initially, then sleeps and wakes regularly to resync
mode = "passive"
# No updates will be auto-installed
auto_update = "none"
# Don't save pending local transactions to disk to be restored whenever the node restarts.
no_persistent_txqueue = true

[rpc]
#  JSON-RPC will be listening for connections on IP 127.0.0.1.
interface = "127.0.0.1"

[footprint]
# Prune old state data. Maintains journal overlay - fast but extra 50MB of memory used.
pruning = "fast"
# Will keep up to 25 MB old state entries.
pruning_memory = 25
# If defined will never use more then 200MB for all caches. (Overrides other cache settings).
cache_size = 200
